"""empty message

Revision ID: 1972c6398e26
Revises: f03c47f191d9
Create Date: 2019-06-21 21:36:20.830477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1972c6398e26'
down_revision = 'f03c47f191d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nascimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nascimento')
    # ### end Alembic commands ###
