"""empty message

Revision ID: 2fefb687c452
Revises: 1972c6398e26
Create Date: 2019-06-21 22:53:03.574837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fefb687c452'
down_revision = '1972c6398e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cidade', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cidade')
    # ### end Alembic commands ###
