"""empty message

Revision ID: 4ca96a98ceb4
Revises: fbd93db40448
Create Date: 2019-07-01 00:23:56.456071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca96a98ceb4'
down_revision = 'fbd93db40448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prod_nome', sa.String(length=64), nullable=True),
    sa.Column('prod_classe', sa.String(length=64), nullable=True),
    sa.Column('prod_autor', sa.String(length=64), nullable=True),
    sa.Column('prod_preco', sa.String(length=20), nullable=True),
    sa.Column('prod_estoque', sa.String(length=20), nullable=True),
    sa.Column('prod_imagem', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    # ### end Alembic commands ###
